/**
 *  @file mmapBridge.h
 *  @brief Memory-mapped file bridge that passes fixed-size messages between processes
 *  (code generated by AmmMessages, a tool that generates code that can span messages across computers).
 *
 *  A "bridge" is a regular file memory-mapped by a writing process and a reading process,
 *  used to pass one fixed-size message at a time. The file is not used by the
 *  SharedMemoryVideoBuffers library or its example programs.
 *  @author Ammar Qammaz (AmmarkoV)
 */

/*
 * This file was automatically generated @ 05-12-2018 18:43:28 using AmmMessages v1.00004
 * https://github.com/AmmarkoV/AmmarServer/tree/master/src/AmmMessages
 * Please note that changes you make here may be automatically overwritten
 * if the AmmMessages generator runs again..!
 */


#ifndef MMAPBRIDGE_H_INCLUDED
#define MMAPBRIDGE_H_INCLUDED


#include <stdlib.h>


#define NORMAL   "\033[0m"      ///< ANSI escape: reset terminal color
#define BLACK   "\033[30m"      ///< ANSI escape: black text
#define RED     "\033[31m"      ///< ANSI escape: red text
#define GREEN   "\033[32m"      ///< ANSI escape: green text
#define YELLOW  "\033[33m"      ///< ANSI escape: yellow text
#define BLUE    "\033[34m"      ///< ANSI escape: blue text
#define MAGENTA "\033[35m"      ///< ANSI escape: magenta text
#define CYAN    "\033[36m"      ///< ANSI escape: cyan text
#define WHITE   "\033[37m"      ///< ANSI escape: white text


#ifdef __cplusplus
extern "C"
{
#endif

/** @brief State of one end (reading or writing) of a memory-mapped file bridge. */
struct bridgeContext
{
  int mode; ///< 0 = not working - 1 = read , 2 = write
  int fd;   ///< Descriptor of the mapped file
  void * map; ///< Start of the mapping (dataSize bytes)
  size_t dataSize; ///< Size of the mapping and of one message, in bytes
  unsigned long lastMsgTimestamp; ///< Timestamp of the last message seen (not used by mmapBridge.c)
  void * callbackOnNewData; ///< Callback for new messages (not used by mmapBridge.c)
};

/** @brief Header at the start of a bridge message. */
struct bridgePayloadHeader
{
   unsigned long timestampInit; ///< Timestamp of the message
};

/**
 * @brief Finds the first two consecutive newline characters (an empty line) or NUL in a buffer, and terminates the string there.
 * @param request Buffer to search; modified in place.
 * @param requestLength Number of bytes in request.
 * @param[out] endOfLine Offset of the terminator written into request.
 * @return Pointer two bytes past the terminator (just after the two newlines), or request itself if nothing was found or an argument is invalid.
 */
char * strstrDoubleNewline(char * request,unsigned int requestLength,unsigned int * endOfLine);

/**
 * @brief Creates (or truncates) a file of sizeOfBridgeMsg bytes and maps it for writing.
 * @param nbc Bridge to initialize.
 * @param fileDescriptor Path of the file to create.
 * @param sizeOfBridgeMsg Message size in bytes.
 * @return 1 on success, 0 on failure.
 */
int initializeWritingBridge(struct bridgeContext * nbc ,const char * fileDescriptor,unsigned int sizeOfBridgeMsg);
/**
 * @brief Zeroes the whole message of a bridge.
 * @param nbc Bridge initialized with initializeWritingBridge().
 * @return 1 on success, 0 if nbc is NULL or not initialized for writing.
 */
int clearWritingBridge(struct bridgeContext * nbc);
/**
 * @brief Copies a message into a bridge.
 * @param nbc Bridge initialized with initializeWritingBridge().
 * @param data Message to copy.
 * @param dataSize Bytes to copy, at most the bridge's dataSize.
 * @param waitForAcknowledgmentXMilliseconds Not implemented: a non-zero value only prints a warning.
 * @return 1 on success, 0 on failure (including a bridge not initialized for writing or dataSize too large).
 */
int writeBridge(struct bridgeContext * nbc , void * data , unsigned int dataSize, unsigned int waitForAcknowledgmentXMilliseconds);
/**
 * @brief Unmaps and closes the file of a writing bridge. The file is closed even if unmapping fails.
 * @param nbc Bridge to close.
 * @return 1 on success, 0 on failure (including a bridge that isn't initialized or is already closed).
 */
int closeWritingBridge(struct bridgeContext * nbc);



/**
 * @brief Maps an existing bridge file read-only. Fails if the file is smaller than one message.
 * @param nbc Bridge to initialize.
 * @param fileDescriptor Path of the file, as created by initializeWritingBridge().
 * @param sizeOfBridgeMsg Message size in bytes.
 * @return 1 on success, 0 on failure.
 */
int initializeReadingBridge(struct bridgeContext * nbc ,const char * fileDescriptor,unsigned int sizeOfBridgeMsg);
/**
 * @brief Copies the current message out of a bridge.
 * @param nbc Initialized bridge (reading or writing).
 * @param[out] data Buffer receiving the message.
 * @param dataSize Bytes to copy, at most the bridge's dataSize.
 * @return 1 on success, 0 on failure (including dataSize too large).
 */
int readBridge(struct bridgeContext * nbc,void * data , unsigned int dataSize );

/**
 * @brief Unmaps and closes the file of a reading bridge. The file is closed even if unmapping fails.
 * @param nbc Bridge to close.
 * @return 1 on success, 0 on failure (including a bridge that isn't initialized or is already closed).
 */
int closeReadingBridge(struct bridgeContext * nbc);

#ifdef __cplusplus
}
#endif


#endif // MMAPBRIDGE_H_INCLUDED
